### PR TITLE
Modify endpoints in own server section of AWS S3

### PR DESCRIPTION
**Pull request by nerg4l**
The first PR to change the endpoints in the documentation.

https://github.com/transloadit/uppy/blob/960362b373666b18a6970f3778ee1440176975af/packages/%40uppy/companion/src/server/controllers/s3.js#L439-L447

Related to #213

### CODE REVIEW

**Review by Murderlon — COMMENTED** [review]
Thanks for making a PR.

Now that I think about it, does it make sense to duplicate endpoints of the example? I feel like it's just likely to get out of date again.

Some alternatives:
1. Instead of writing the endpoints and a link the example root, we can also create to steps:
   1. [Setup Uppy client](https://github.com/transloadit/uppy/blob/main/examples/aws-nodejs/public/index.html)
   2. [Setup your server](https://github.com/transloadit/uppy/blob/main/examples/aws-nodejs/index.js)
2. Or we keep the HTTP methods but remove the specific endpoints and add a sentence above that you need you need these endpoints but it's up to you to decide under which route they fall, as long as you keep it in sync with Uppy.

What do you think?

**Comment by nerg4l** [comment]
I'm still getting familiar with the available Uppy components.

These endpoints will only change if `@uppy/companion` changes, am I wrong?

I think `@uppy/aws-s3-multipart` could be used for the "Setup Uppy client". That component has a predefined set of routes.

Also, `@uppy/companion` has great documentation for the routes. Example: https://github.com/transloadit/uppy/blob/960362b373666b18a6970f3778ee1440176975af/packages/%40uppy/companion/src/server/controllers/s3.js#L36-L50
Maybe it's enough to put these somewhere in the documentation.

**Comment by Murderlon** [comment]
> These endpoints will only change if `@uppy/companion` changes, am I wrong?

No we are updating the section on using it with your own server. At the moment the endpoints don't matter at all. For instance in `createMultipartUpload` you have to use `fetch` to your own backend. You're in control what endpoint you fetch, not Uppy.

As discussed before we should change the property name from `companionUrl` to `endpoint` and document what to do _exactly_ so you don't have to write this all manually. But until this in there, we need to write docs for the current reality, brining me back to my two suggestions above.

**Comment by nerg4l** [comment]
From a user's point of view, I think the first option would be better.

**Comment by Murderlon** [comment]
Would you like to make the change?

**Comment by nerg4l** [comment]
I will update this PR later today. I can only work on it outside of European working hours.

**Review by Murderlon — APPROVED** [review]

**Pull request merged**
