### PR TITLE
CDN version: use package.json from uppy

### PR DESCRIPTION
**Pull request by arturi**

### CODE REVIEW

**Review by Murderlon — COMMENTED** [review]
This is way simpler than a cross-repo GH Action, makes sense 👍 

Two things:
- We should make `uppy` a dev dependency as we only use it at build time
- We need to configure dependabot to immediately make a PR for any version bump of `uppy`.

**Comment by aduh95** [comment]
I don't have access to the repo settings for Dependabot. Note that we might want to have some automation anyway as we want to merge the doc PR as soon as a new Uppy version is released, so it might make sense to build something custom.

**Comment by aduh95** [comment]
> * We need to configure dependabot to immediately make a PR for any version bump of `uppy`.

This can be considered done now that we have the `update-deps` action I think.

**Comment by Murderlon** [comment]
@arturi just the dev dep comment then 👍

**Review by Murderlon — APPROVED** [review]

**Pull request merged**
