### PR TITLE
Use prettier spaces intead of tabs to fix code blocks

### PR DESCRIPTION
**Pull request by Murderlon**

### CODE REVIEW

**Comment by aduh95** [comment]
What does it mean "to fix code blocks"?

**Comment by Murderlon** [comment]
To not have enormous spacing:

Screenshot 2023-11-30 at 14 14 27

Unfortunately no Docusaurus option for this to solving it with spaces.

**Comment by aduh95** [comment]
Wouldn't https://caniuse.com/css3-tabsize be the thing we need?

**Comment by Murderlon** [comment]
Just tested it on the website and that works too. Maybe better to try that indeed.

**Pull request closed without merging**
